/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://5jrs6jszyja4dg2qciaozlrgku.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-73cwgshn45eshjdazvq7xhkzfy",
    "aws_cognito_identity_pool_id": "us-west-2:0445b6ee-3e21-4a19-9244-a998e9111cfc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_bJRQJPQ8f",
    "aws_user_pools_web_client_id": "1jm0q4cgjkno06bljt05acr4as",
    "oauth": {}
};


export default awsmobile;
